### ISSUE TITLE
Link to Issue Reporting 404 Error

### ISSUE THREAD

**Issue by szklenskij** [Allegheny-Computer-Science-302-S2019/cs302-S2019-practical3-starter-final#1]
@gkapfham The "Computer Science 302 Practical 3 Starter" link to report an issue in the Problems section of the ReadMe of the cs302-S2019-practical3-starter GitHub page leads to a 404 error.

**Comment by gkapfham** [comment]
Hello @szklenskij, thanks for pointing out this problem. I have resolved the issue! If you notice other problems with this repository or if you think that I did not correctly fix the issue, please let me know. Thanks!
